packages:
  - app/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - "@heroui/shared-utils"
