#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/

pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.{js,ts,jsx,tsx}"
      run: pnpm format {staged_files}
