#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/

pre-commit:
  parallel: true
  jobs:
    - name: format frontend app game
      root: "frontend/app/kansha-game"
      glob: "*.{js,ts,jsx,tsx}"
      run: pnpm format {staged_files}
